version: '3.7'

services:
    dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: demo-docker-nextjs-dev
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - '3000:3000'
        env_file:
            - .env.local
    prod:
        build:
            context: .
            dockerfile: Dockerfile.prod
        container_name: demo-docker-nextjs
        ports:
            - '3000:3000'
        env_file:
            - .env.local

volumes:
    node_modules:
